import { Domain, Task } from './types';

export const DOMAINS: Domain[] = [
  {
    id: 'robo-logic',
    name: 'Space Explorer Quest',
    icon: 'Bot',
    color: 'from-blue-600 to-indigo-600', // Royal Blue: #2E4EDB / Sky Blue: #7FC7F5
    bgColor: 'bg-blue-50',
    borderColor: 'border-blue-300',
    description: 'Help Bit the Code Bot navigate Space Explorer grids, dodge asteroids, and charge the engine!',
    storyContext: 'Bit has arrived at the Space Explorer station. Help him gather Magic Crystals and input the perfect command sequence to repair the motherboard!',
  },
  {
    id: 'frontend-magic',
    name: 'Magic Kingdom Spellbook',
    icon: 'Sparkles',
    color: 'from-purple-500 to-pink-500', // Purple: #8A5FD6 / Pastel Pink: #F5A9CD
    bgColor: 'bg-purple-50',
    borderColor: 'border-purple-300',
    description: 'Join Princess Luna and Wizard Byte to design magical flying castles using HTML and CSS spells!',
    storyContext: 'The magic spell scrolls are blank! Help Wizard Byte cast HTML header spells and CSS color potions to restore the castle walls!',
  },
  {
    id: 'python-safari',
    name: 'Pirate Island Safari',
    icon: 'Compass',
    color: 'from-amber-400 to-yellow-500', // Golden Yellow: #F5C24C
    bgColor: 'bg-amber-50',
    borderColor: 'border-amber-300',
    description: 'Explore Pirate Island with Captain Loop and solve python coordinates to unlock the magic treasure chest!',
    storyContext: 'Captain Loop has lost his treasure map. Guide him with Python syntax variables and loops to avoid dangerous stone obstacles and retrieve the gold!',
  }
];

export const TASKS_BY_DOMAIN: Record<string, Task[]> = {
  'robo-logic': [
    {
      id: 1,
      title: 'The Empty Treasure',
      story: 'Bit arrived at the Space Explorer outpost but found the code box completely empty! Let’s take his first electric steps to scan the treasure core.',
      objective: 'Program Bit to move forward 2 cells to reach the chest scanner.',
      defaultBlocks: ['Move Forward', 'Turn Right', 'Turn Left'],
      correctBlocks: ['Move Forward', 'Move Forward'],
      points: 100,
      mascotExpr: 'thinking',
      gridSize: { rows: 5, cols: 5 },
      startPos: { x: 1, y: 2 },
      targetPos: { x: 3, y: 2 },
      obstacles: [],
    },
    {
      id: 2,
      title: 'Magic Box',
      story: 'A holographic Magic Box is locked! We need to bypass a floating asteroid to step on the unlock sensor.',
      objective: 'Move forward, turn right, move forward, and turn left to reach the Magic Box.',
      defaultBlocks: ['Move Forward', 'Turn Right', 'Turn Left'],
      correctBlocks: ['Move Forward', 'Turn Right', 'Move Forward', 'Turn Left', 'Move Forward'],
      points: 110,
      mascotExpr: 'thinking',
      gridSize: { rows: 5, cols: 5 },
      startPos: { x: 1, y: 3 },
      targetPos: { x: 3, y: 2 },
      obstacles: [{ x: 2, y: 3 }],
    },
    {
      id: 3,
      title: 'Count the Stars',
      story: 'Look at all those glowing starlight sensors! Writing "Move Forward" over and over is tiring. Let’s use a loop block!',
      objective: 'Utilize the Repeat block to walk 4 times forward and count the stars.',
      defaultBlocks: ['Move Forward', 'Repeat 4x', 'Turn Left'],
      correctBlocks: ['Repeat 4x', 'Move Forward'],
      points: 120,
      mascotExpr: 'happy',
      gridSize: { rows: 6, cols: 6 },
      startPos: { x: 1, y: 2 },
      targetPos: { x: 5, y: 2 },
      obstacles: [],
    },
    {
      id: 4,
      title: 'Wizard’s Potion',
      story: 'Wizard Byte left a fuel potion behind. We must zig-zag around chemical gas vents to secure it for the spaceship booster.',
      objective: 'Perform a sequence of forward-turn-forward motions to zig-zag to the potion.',
      defaultBlocks: ['Move Forward', 'Turn Right', 'Turn Left'],
      correctBlocks: ['Move Forward', 'Turn Right', 'Move Forward', 'Turn Left', 'Move Forward', 'Turn Right', 'Move Forward'],
      points: 130,
      mascotExpr: 'thinking',
      gridSize: { rows: 5, cols: 5 },
      startPos: { x: 1, y: 4 },
      targetPos: { x: 3, y: 2 },
      obstacles: [{ x: 2, y: 4 }, { x: 1, y: 3 }, { x: 3, y: 3 }],
    },
    {
      id: 5,
      title: 'Crystal Cave',
      story: 'The starlight tunnel contains glowing energy crystals. Grab them both to supercharge Bit’s battery core.',
      objective: 'Step forward, grab the crystal, then move to the destination portal.',
      defaultBlocks: ['Move Forward', 'Turn Right', 'Turn Left', 'Repeat 2x'],
      correctBlocks: ['Move Forward', 'Turn Right', 'Move Forward', 'Turn Left', 'Move Forward'],
      points: 140,
      mascotExpr: 'happy',
      gridSize: { rows: 5, cols: 5 },
      startPos: { x: 2, y: 4 },
      targetPos: { x: 2, y: 1 },
      obstacles: [{ x: 1, y: 2 }, { x: 3, y: 2 }],
    },
    {
      id: 6,
      title: 'Magic Backpack',
      story: 'We found Captain Loop’s variable storage backpack! Program Bit to walk forward and retrieve the logical circuit key.',
      objective: 'Walk 3 steps, turn right, and walk 2 steps to secure the backpack.',
      defaultBlocks: ['Move Forward', 'Turn Right', 'Turn Left', 'Repeat 3x'],
      correctBlocks: ['Repeat 3x', 'Move Forward', 'Turn Right', 'Move Forward', 'Move Forward'],
      points: 150,
      mascotExpr: 'victory',
      gridSize: { rows: 6, cols: 6 },
      startPos: { x: 1, y: 1 },
      targetPos: { x: 4, y: 3 },
      obstacles: [{ x: 2, y: 2 }, { x: 3, y: 1 }],
    },
    {
      id: 7,
      title: 'Lost Unicorn',
      story: 'The stellar unicorn star core is blocked! Bit must step on the safety switch to release the magnetic locks.',
      objective: 'Step on the switch to unlock the gates and reach the unicorn sensor.',
      defaultBlocks: ['Move Forward', 'Turn Right', 'Turn Left', 'Repeat 2x'],
      correctBlocks: ['Move Forward', 'Turn Left', 'Move Forward', 'Turn Right', 'Move Forward'],
      points: 160,
      mascotExpr: 'thinking',
      gridSize: { rows: 5, cols: 5 },
      startPos: { x: 2, y: 3 },
      targetPos: { x: 4, y: 1 },
      obstacles: [{ x: 3, y: 3 }, { x: 2, y: 2 }],
    },
    {
      id: 8,
      title: 'Ancient Spell',
      story: 'This canyon is narrow and windy. Enter the perfect algorithm to maneuver Bit without scratching his shiny alloy paint!',
      objective: 'Follow the winding alleyway path safely to the end console.',
      defaultBlocks: ['Move Forward', 'Turn Right', 'Turn Left'],
      correctBlocks: ['Move Forward', 'Turn Right', 'Move Forward', 'Turn Left', 'Move Forward', 'Turn Left', 'Move Forward', 'Turn Right', 'Move Forward'],
      points: 170,
      mascotExpr: 'thinking',
      gridSize: { rows: 6, cols: 6 },
      startPos: { x: 1, y: 4 },
      targetPos: { x: 4, y: 2 },
      obstacles: [{ x: 1, y: 3 }, { x: 2, y: 3 }, { x: 3, y: 4 }, { x: 3, y: 3 }],
    },
    {
      id: 9,
      title: 'Bridge of Logic',
      story: 'The bridge is extremely long. Cross the light bridge panels using nested stepping sequences!',
      objective: 'Navigate the grid using precise turns and forward loops.',
      defaultBlocks: ['Move Forward', 'Turn Right', 'Repeat 3x', 'Repeat 2x'],
      correctBlocks: ['Repeat 3x', 'Move Forward', 'Turn Right', 'Move Forward'],
      points: 180,
      mascotExpr: 'happy',
      gridSize: { rows: 5, cols: 5 },
      startPos: { x: 1, y: 3 },
      targetPos: { x: 4, y: 3 },
      obstacles: [{ x: 2, y: 2 }, { x: 3, y: 2 }],
    },
    {
      id: 10,
      title: 'Dragon Castle',
      story: 'The launch rocket is fully fueled, but the master mainframe is active! Help Bit reach the cockpit core to lift off!',
      objective: 'Avoid the solar heat vents, plug into the cockpit console, and complete the adventure!',
      defaultBlocks: ['Move Forward', 'Turn Right', 'Turn Left', 'Repeat 3x'],
      correctBlocks: ['Move Forward', 'Turn Left', 'Move Forward', 'Move Forward', 'Turn Right', 'Move Forward', 'Move Forward'],
      points: 200,
      mascotExpr: 'victory',
      gridSize: { rows: 6, cols: 6 },
      startPos: { x: 1, y: 4 },
      targetPos: { x: 4, y: 1 },
      obstacles: [{ x: 2, y: 3 }, { x: 3, y: 3 }, { x: 3, y: 2 }],
    }
  ],
  'frontend-magic': [
    {
      id: 1,
      title: 'The Empty Treasure',
      story: 'Princess Luna wants to label her magic chest with a massive, bold header spell: "MY TREASURE". Let’s write the HTML tag!',
      objective: 'Select the correct header element block.',
      defaultBlocks: ['<h1>', '<p>', '<div>', '<img>'],
      correctBlocks: ['<h1>'],
      points: 100,
      mascotExpr: 'thinking',
      gridSize: { rows: 3, cols: 3 },
      startPos: { x: 1, y: 1 },
      targetPos: { x: 2, y: 2 },
      obstacles: [],
    },
    {
      id: 2,
      title: 'Magic Box',
      story: 'We need a visual box container to group all our gold coins together. Let’s declare a divider tag!',
      objective: 'Select the HTML layout divider block.',
      defaultBlocks: ['<div>', '<span>', '<img>', '<h1>'],
      correctBlocks: ['<div>'],
      points: 110,
      mascotExpr: 'thinking',
      gridSize: { rows: 3, cols: 3 },
      startPos: { x: 1, y: 1 },
      targetPos: { x: 2, y: 2 },
      obstacles: [],
    },
    {
      id: 3,
      title: 'Count the Stars',
      story: 'Let’s display a list of stars. Which tag declares a list item inside our HTML magic scroll?',
      objective: 'Select the list item element.',
      defaultBlocks: ['<li>', '<ul>', '<a>', '<p>'],
      correctBlocks: ['<li>'],
      points: 120,
      mascotExpr: 'happy',
      gridSize: { rows: 3, cols: 3 },
      startPos: { x: 1, y: 1 },
      targetPos: { x: 2, y: 2 },
      obstacles: [],
    },
    {
      id: 4,
      title: 'Wizard’s Potion',
      story: 'Wizard Byte wants his potion bowl styled purple. Let’s cast a Hex Color style rule!',
      objective: 'Select the purple hex color rule.',
      defaultBlocks: ['color: #8A5FD6', 'color: #F5C24C', 'color: #2E4EDB', 'color: #4CAF7D'],
      correctBlocks: ['color: #8A5FD6'],
      points: 130,
      mascotExpr: 'thinking',
      gridSize: { rows: 3, cols: 3 },
      startPos: { x: 1, y: 1 },
      targetPos: { x: 2, y: 2 },
      obstacles: [],
    },
    {
      id: 5,
      title: 'Crystal Cave',
      story: 'We want to project an illustration of the glowing Crystal Cave. Which HTML element displays images?',
      objective: 'Select the image tag element.',
      defaultBlocks: ['<img>', '<video>', '<a>', '<div>'],
      correctBlocks: ['<img>'],
      points: 140,
      mascotExpr: 'happy',
      gridSize: { rows: 3, cols: 3 },
      startPos: { x: 1, y: 1 },
      targetPos: { x: 2, y: 2 },
      obstacles: [],
    },
    {
      id: 6,
      title: 'Magic Backpack',
      story: 'Let’s change the background color of our magic backpack card to a soft stardust yellow!',
      objective: 'Choose the background-color rule.',
      defaultBlocks: ['background-color: #F5C24C', 'border-color', 'font-size', 'margin'],
      correctBlocks: ['background-color: #F5C24C'],
      points: 150,
      mascotExpr: 'victory',
      gridSize: { rows: 3, cols: 3 },
      startPos: { x: 1, y: 1 },
      targetPos: { x: 2, y: 2 },
      obstacles: [],
    },
    {
      id: 7,
      title: 'Lost Unicorn',
      story: 'The unicorn is standing too close to the forest trees! Add outer spacing to separate them.',
      objective: 'Select the correct outer margin spacing property.',
      defaultBlocks: ['margin', 'padding', 'width', 'border'],
      correctBlocks: ['margin'],
      points: 160,
      mascotExpr: 'thinking',
      gridSize: { rows: 3, cols: 3 },
      startPos: { x: 1, y: 1 },
      targetPos: { x: 2, y: 2 },
      obstacles: [],
    },
    {
      id: 8,
      title: 'Ancient Spell',
      story: 'Make the ancient scroll heading text look strong, heavy, and bold!',
      objective: 'Select the bold text formatting tag.',
      defaultBlocks: ['<strong>', '<em>', '<br>', '<small>'],
      correctBlocks: ['<strong>'],
      points: 170,
      mascotExpr: 'thinking',
      gridSize: { rows: 3, cols: 3 },
      startPos: { x: 1, y: 1 },
      targetPos: { x: 2, y: 2 },
      obstacles: [],
    },
    {
      id: 9,
      title: 'Bridge of Logic',
      story: 'Let’s align the stepping stones nicely side-by-side using CSS flexbox layout!',
      objective: 'Select the display flex rule to layout items.',
      defaultBlocks: ['display: flex', 'display: block', 'display: none', 'display: grid'],
      correctBlocks: ['display: flex'],
      points: 180,
      mascotExpr: 'happy',
      gridSize: { rows: 3, cols: 3 },
      startPos: { x: 1, y: 1 },
      targetPos: { x: 2, y: 2 },
      obstacles: [],
    },
    {
      id: 10,
      title: 'Dragon Castle',
      story: 'Create a magic link scroll to teleport Princess Luna straight into the Dragon Castle courtyard!',
      objective: 'Select the HTML anchor hyperlink element block.',
      defaultBlocks: ['<a>', '<button>', '<p>', '<div>'],
      correctBlocks: ['<a>'],
      points: 200,
      mascotExpr: 'victory',
      gridSize: { rows: 3, cols: 3 },
      startPos: { x: 1, y: 1 },
      targetPos: { x: 2, y: 2 },
      obstacles: [],
    }
  ],
  'python-safari': [
    {
      id: 1,
      title: 'The Empty Treasure',
      story: 'Let’s help Captain Loop say "Found it!" using Python’s screen speech function.',
      objective: 'Arrange the tokens to construct a valid print statement.',
      defaultBlocks: ['print', '(', '"Found it!"', ')'],
      correctBlocks: ['print', '(', '"Found it!"', ')'],
      points: 100,
      mascotExpr: 'happy',
      gridSize: { rows: 3, cols: 3 },
      startPos: { x: 1, y: 1 },
      targetPos: { x: 2, y: 2 },
      obstacles: [],
    },
    {
      id: 2,
      title: 'Magic Box',
      story: 'Let’s store our golden coins inside a computer variable named "gold"!',
      objective: 'Set variable gold equal to 10.',
      defaultBlocks: ['gold', '=', '10', 'print'],
      correctBlocks: ['gold', '=', '10'],
      points: 110,
      mascotExpr: 'thinking',
      gridSize: { rows: 3, cols: 3 },
      startPos: { x: 1, y: 1 },
      targetPos: { x: 2, y: 2 },
      obstacles: [],
    },
    {
      id: 3,
      title: 'Count the Stars',
      story: 'Write a loop that will count 4 stars in the sky automatically.',
      objective: 'Choose the Python range loop sequence.',
      defaultBlocks: ['for i in range(4):', 'for i in stars:', 'while stars < 4:', 'loop 4x'],
      correctBlocks: ['for i in range(4):'],
      points: 120,
      mascotExpr: 'happy',
      gridSize: { rows: 3, cols: 3 },
      startPos: { x: 1, y: 1 },
      targetPos: { x: 2, y: 2 },
      obstacles: [],
    },
    {
      id: 4,
      title: 'Wizard’s Potion',
      story: 'Combine 3 red droplets and 5 blue droplets to find the total potion droplets!',
      objective: 'Select the formula to calculate droplets.',
      defaultBlocks: ['droplets = 3 + 5', 'droplets = 3 * 5', 'droplets = 3 - 5', 'droplets = 5 / 3'],
      correctBlocks: ['droplets = 3 + 5'],
      points: 130,
      mascotExpr: 'thinking',
      gridSize: { rows: 3, cols: 3 },
      startPos: { x: 1, y: 1 },
      targetPos: { x: 2, y: 2 },
      obstacles: [],
    },
    {
      id: 5,
      title: 'Crystal Cave',
      story: 'Check if the cave door is open using a true or false Boolean variable.',
      objective: 'Set variable is_open to True.',
      defaultBlocks: ['is_open = True', 'is_open = "True"', 'is_open = false', 'is_open = 1'],
      correctBlocks: ['is_open = True'],
      points: 140,
      mascotExpr: 'happy',
      gridSize: { rows: 3, cols: 3 },
      startPos: { x: 1, y: 1 },
      targetPos: { x: 2, y: 2 },
      obstacles: [],
    },
    {
      id: 6,
      title: 'Magic Backpack',
      story: 'Let’s create a list to store our backpack items: "key" and "map"!',
      objective: 'Assemble the Python list variable.',
      defaultBlocks: ['items = ["key", "map"]', 'items = "key", "map"', 'items = {key, map}', 'items = list()'],
      correctBlocks: ['items = ["key", "map"]'],
      points: 150,
      mascotExpr: 'victory',
      gridSize: { rows: 3, cols: 3 },
      startPos: { x: 1, y: 1 },
      targetPos: { x: 2, y: 2 },
      obstacles: [],
    },
    {
      id: 7,
      title: 'Lost Unicorn',
      story: 'If the unicorn is found, print a celebratory chime!',
      objective: 'Select the correct Python "if" logic block.',
      defaultBlocks: ['if unicorn == True:', 'if unicorn is True', 'when unicorn:', 'check unicorn:'],
      correctBlocks: ['if unicorn == True:'],
      points: 160,
      mascotExpr: 'thinking',
      gridSize: { rows: 3, cols: 3 },
      startPos: { x: 1, y: 1 },
      targetPos: { x: 2, y: 2 },
      obstacles: [],
    },
    {
      id: 8,
      title: 'Ancient Spell',
      story: 'Measure the length of the spell word using Python’s length function.',
      objective: 'Call len() on the spell variable.',
      defaultBlocks: ['len(spell)', 'spell.length()', 'count(spell)', 'spell.size'],
      correctBlocks: ['len(spell)'],
      points: 170,
      mascotExpr: 'thinking',
      gridSize: { rows: 3, cols: 3 },
      startPos: { x: 1, y: 1 },
      targetPos: { x: 2, y: 2 },
      obstacles: [],
    },
    {
      id: 9,
      title: 'Bridge of Logic',
      story: 'Keep walking across the logic bridge panel while the step count is less than 5.',
      objective: 'Select the correct while-loop statement.',
      defaultBlocks: ['while steps < 5:', 'for steps < 5:', 'loop while steps:', 'until steps == 5:'],
      correctBlocks: ['while steps < 5:'],
      points: 180,
      mascotExpr: 'happy',
      gridSize: { rows: 3, cols: 3 },
      startPos: { x: 1, y: 1 },
      targetPos: { x: 2, y: 2 },
      obstacles: [],
    },
    {
      id: 10,
      title: 'Dragon Castle',
      story: 'Let’s define a custom spell function named "launch_rocket" to finish our grand safari adventure!',
      objective: 'Select the correct python function definition header.',
      defaultBlocks: ['def launch_rocket():', 'function launch_rocket():', 'define launch_rocket:', 'void launch_rocket():'],
      correctBlocks: ['def launch_rocket():'],
      points: 200,
      mascotExpr: 'victory',
      gridSize: { rows: 3, cols: 3 },
      startPos: { x: 1, y: 1 },
      targetPos: { x: 2, y: 2 },
      obstacles: [],
    }
  ]
};

export const MASCOTS = {
  robo: {
    name: 'Bit',
    species: 'Code Bot',
    happy: '🤖✨',
    thinking: '🤖💬',
    sad: '🤖🩹',
    victory: '🤖🎉',
    accentColor: 'text-blue-600',
    bubbleColor: 'bg-blue-50 text-blue-900 border-blue-200'
  },
  wizard: {
    name: 'Wizard Byte',
    species: 'Stardust Wizard',
    happy: '🧙‍♂️✨',
    thinking: '🧙‍♂️🔮',
    sad: '🧙‍♂️💤',
    victory: '🧙‍♂️🌟',
    accentColor: 'text-purple-600',
    bubbleColor: 'bg-purple-50 text-purple-900 border-purple-200'
  },
  explorer: {
    name: 'Captain Loop',
    species: 'Pirate Captain',
    happy: '🏴‍☠️✨',
    thinking: '🏴‍☠️💬',
    sad: '🏴‍☠️🩹',
    victory: '🏴‍☠️🏆',
    accentColor: 'text-amber-600',
    bubbleColor: 'bg-amber-50 text-amber-900 border-amber-200'
  }
};
